### ISSUE TITLE
"cannot override this color" 

### ISSUE THREAD

**Issue by DjinnDjab** [Mahmud0808/ColorBlendr#104]
cannot override the first column colors, error message says. i feel like i was able to before updating to 1.5. also, in the google messages app, when I open a conversation, the background color of that conversation is not a color that is on the color picker anywhere at all so I'm unsure how to change it LOL. and with none of the colors being mapped or telling you what they will actually change, it's just a total nightmare, I've been playing around with this theme I've been making for like a month and I feel like each time it gets wonkier and wonkier when I update colors and stuff but the biggest thing is I see elements that have a color that are not selected anywhere in the color picker

**Comment by Mahmud0808** [comment]
First and last row has been disabled in v1.5 because it wasn't actually changing (saving) the color when I checked. Also with Google's latest material library, apps now generate their own color palettes based on one single color from system color palette. That's why you see some colors which you don't even have on your system palette. What you can do is to find that color resource using FabricateOverlay app (can be found on GitHub), but it's very tiresome work because you'll need to put random colors on each resource and then find the one you are looking for. Then I can include that resource in ColorBlendr to be themed automatically. I already did it for a lot of google apps to make them pitch black, it took sometime but it worked in my case.

**Comment by DjinnDjab** [comment]
they did work for me, now my gboard has white keys and I'm unable to change
them. whats interesting is the shade that is appearing in my messages
background, that I can't find in the pallette, is actually one of the
colors im using, like i changed it on the pallette but for some reason the
change didnt make it to the UI. i feel like that's kind of a thing and its
kinda random? idk something is weird here and it's unfortunate bc this
was/is the closest ive gotten to having my Ui just the way I want. im still
gonna use it cause it's better than nothing but im always gonna feel some
kinda way about it 😂 thanks for  your work on this app i do appreciate you
taking the time to kindly respond as well
