### ISSUE TITLE
Custom background lightness for light mode and dark mode 

### ISSUE THREAD

**Issue by keyjeyelpi** [Mahmud0808/ColorBlendr#108]
Would it be possible to implement custom background lightness for light mode and dark mode? Here is somewhat of a preview of what I'm asking for:

![Screenshot_2024-07-23-05-56-35-604_com drdisagree colorblendr](https://github.com/user-attachments/assets/cd48f2b5-389b-4b16-ba7a-8dc968ffe28e)
![Screenshot_2024-07-23-05-58-04-502_com drdisagree colorblendr](https://github.com/user-attachments/assets/e2b744be-e269-4288-b353-8ce0bc35cab3)

Thank you

**Comment by Mahmud0808** [comment]
It is actually very easily do-able but it will just bloat the app imo.

**Comment by e-t-l** [comment]
Would it be an equally easy enhancement to make the Mode-Specific Theme change the "Styles" preset when operating without root?

Since root is required to tweak the levels of brightness etc, when using ColorBlendr without root it could instead change the Styles preset to `Neutral` (since that one seems to produce more dark/muted colors than any of the other presets, like `Monochrome` or `Tonal Spot`...)

What do you think?
