### ISSUE TITLE
Shizuku support for non-rooted users 

### ISSUE THREAD

**Issue by Zaxx69** [Mahmud0808/ColorBlendr#22]
Please implement shizuku support for the app so that non-rooted users can also get the benefits of this app

**Comment by Derpitron** [comment]
I don't think it's possible for non-rooted even with Shizuku. Since android 12.1, Google patched the loophole that let system users/adb apply custom Material You palettes (custom overlays I think) systemwide. Not even the incumbent theming app Repainter.app could circumvent these limits with Shizuku.

Your unrooted theming capacity is limited by the rom you use. According to Repainter.app, Pixel 3 and Samsung One UI are most compatible/capable with unrooted theming.

I hope I am wrong though.

**Comment by Mahmud0808** [comment]
> I hope I am wrong though.

You are correct.

**Comment by MinekPo1** [comment]
Note that repainter seems to be kinda abandoned. I personally use repainter on a nonrooted device, though I would prefer an open source alternative

**Comment by Zaxx69** [comment]
I also use repainter but it would be great if color blender works on non-rooted devices

**Comment by Derpitron** [comment]
I also use unrooted Repainter and would love to see it, but guys please read my first comment on why unrooted Color Blendr is almost impossible at the time. https://github.com/Mahmud0808/ColorBlendr/issues/22#issuecomment-1891017249

**Comment by Zaxx69** [comment]
Ok bro i understand

**Comment by keagxn** [comment]
I had repainted working up until OneUi 5, when I updated to 6 it broke. I somehow got it working again when it installed a security patch but it broke again when I turned off color palette and hasn't working since. If someone can add shizuku support for OneUI i'll literally buy them 100 coffees

**Comment by Derpitron** [comment]
you madlad!

**Comment by Zaxx69** [comment]
Arigatoh senpai 🙏
