### ISSUE TITLE
Improvements to "Force per app theme" list

### ISSUE THREAD

**Issue by Username1-a** [Mahmud0808/ColorBlendr#66]
1) It seems that chosen/enabled apps in "Force per app theme" list don't persist when Colorblendr service turns off/on – you need to enable per app theme for needed apps all over again;

2) Since the list shows all system+user apps, the list could be very huge – filtering options for the app list would be helpful (system+user/user/system apps and launchable (only shows system apps that can be opened)/all for system apps filter);

3) Moving chosen/enabled/highlighted apps to the top of the list would help to easier keep track of apps for which this kind of theming is enabled, as opposed to finding them while swiping through the list;

4) As opposed to Colorblendr app itself that needs to be enabled in "Force per app theme" list to correctly see/preview the theme as user makes changes to it in the app (like changing the background brightness), maybe per app theme should be enabled for Colorblendr by default?

**Comment by Mahmud0808** [comment]
### Accepted:

1. https://github.com/Mahmud0808/ColorBlendr/commit/4ffdd39d1156944f50eb15b69b3c9b71ff94c2f1
2. https://github.com/Mahmud0808/ColorBlendr/commit/f476b4be05f04e05db937fdaed3073f97870fdb2
3. https://github.com/Mahmud0808/ColorBlendr/commit/b71a1d8c4d8337c898d9ffd23280ecebc7b20000

### Rejected:

4. This is what I initially did, but someone reported his ColorBlendr app keeps crashing because of it, and he doesn't want it to be selected by default. It was automatically being enabled for him even after disabling (which I couldn't reproduce), hence it's not enabled by default anymore.
5. Backup and restore is already included with the full config. A separate backup is unnecessary. ColorBlendr can automatically update the list based on different conditions (app availability, service enabled/disabled etc).

**Comment by Mahmud0808** [comment]
> > 1. It seems that chosen/enabled apps in "Force per app theme" list don't persist when Colorblendr service turns off/on – you need to enable per app theme for needed apps all over again;
> 
> @Mahmud0808 Sorry for tagging, but it seems that this first issue is still persistent in version 1.4 – after Colorblendr service is turned off and then on the user choice inside "force per app theme" list is cleared, you need to re-enable apps again

Can't reproduce.

**Comment by Mahmud0808** [comment]
Got it, it refreshes the list on each launch. That's what makes it loose the previously selected apps.
